name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation de graphviz
      run: sudo apt-get -y install graphviz
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: ./run1.sh g1
    - name: upload du resultat
      uses: actions/upload-artifact@v4
      with:
        name: gresult
        path: g1.svg
